Feature/ Register-user
spotseeker/app pull request #29
Opened 2024-10-17 21:42 UTC by Davjego

Flujo de registro completo
-falta añadir funcion del image picker
-al final devuelve un objeto con todos los datos del usuario

2024-10-17 21:48 UTC, andres15alvarez requested changes

2024-10-17 21:48 UTC, andres15alvarez commented on Schemas/UserSchema.ts
> +  namee: z
A este campo lo puedes renombrar como firstname

2024-10-17 22:43 UTC, Davjego commented on Schemas/UserSchema.ts
> +  namee: z
Cambio listo.

2024-10-17 23:01 UTC, andres15alvarez approved these changes

2024-10-21 16:20 UTC, clarissaRun approved these changes
aprobado

2024-10-21 16:26 UTC, merged