Feature/9/user-profile
spotseeker/app pull request #30
Opened 2024-10-18 08:00 UTC by clarissaRun

-Agregado folder (tabs) para las secciones de la App en la barra inferior. 
-Pantalla de perfil de usuario 
-Barra superior(en edición para las demás secciones)
-Barra inferior de navegación (edición para demás ventanas)

2024-10-18 16:02 UTC, andres15alvarez reviewed
Tambien completaste la barra de navegacion o solo la dejaste sin los estilos correctos? Ya que @rikardodlpj88 estaba trabajando en esa parte creo, sino para que el se enfoque en otra seccion

2024-10-18 16:02 UTC, andres15alvarez commented on components/CustomButton.tsx
> +    <TouchableOpacity
Por que cambiaste el tipo de componente a TouchableOpacity?

2024-10-18 16:02 UTC, andres15alvarez commented on app/(tabs)/profile.tsx
> +              <View style={{width:'33%', display: 'flex', flexDirection: 'column', gap: 10, justifyContent: 'center', alignItems:'center'}}>
Por que en algunas parte usas className para pasarle los estilos y en otras usas esa prop style?

2024-10-18 19:59 UTC, andres15alvarez requested changes

2024-10-18 19:59 UTC, andres15alvarez commented on components/InfoBox.tsx
> +                </Text>
El fontSize no es de 18 es de 12 segun el figma. Reajusta los demas tamaños tambien

2024-10-20 16:43 UTC, andres15alvarez requested changes

2024-10-20 16:43 UTC, andres15alvarez commented on app/Welcome.tsx
> +              onPress={() => router.push("/(tabs)/profile")}
Pon esto en el login, para que rediriga hacia alla en lugar del link en el signup de ir

2024-10-20 16:43 UTC, andres15alvarez commented on app/(tabs)/profile.tsx
> +              shadowRadius: 4,
Seria eliminar esta sombra @clarissaRun

2024-10-22 19:45 UTC, andres15alvarez approved these changes

2024-10-22 20:07 UTC, Davjego approved these changes

2024-10-22 20:13 UTC, merged